### ISSUE TITLE
Make shortcuts configurable

### ISSUE THREAD

**Issue by yelsayd** [gggritso/Vimmy.safariextension#21]
Ideally through the extension's pane in settings.

**Comment by ghost** [comment]
agree

**Comment by gggritso** [comment]
Which keys would you change, given the chance?

**Comment by ghost** [comment]
like change [control] key to [option] if possible and the key to "move to the previous tab"

**Comment by yelsayd** [comment]
Being greedy aside, if someone goes about doing this, I don't see why selecting a subset of keys makes things easier, they might as well just enable changing all of them, or is there another incentive for doing that?

FWIW, I won't complain if I have the following subset:
- Scrolling up and down the page
- Moving back and forward in history
- Switching to previous and next tab
- Closing current tab
- Opening new tab
- Jumping to links (although I think there's a kinda global agreement on the f shortcut)

I think these cover 95% of my personal use, YMMV.

**Comment by gggritso** [comment]
I thought about it for a while, and even though I’m not opposed, I can’t commit the time right now to do this, nor do I particularly want to. The amount of code for this would eclipse the rest of the codebase.

I guess what I’m saying is that this feature is out of scope for this small extension. If someone else wants to tackle this (or even just fork this extensions), I’ll certainly help them along, but I am not up for working on it myself, sorry!

**Comment by rubenvarela** [comment]
Would you have any pointers or ideas? Maybe just writing down your thoughts?

Just thinking that maybe outlining or just writing your thoughts may help someone if they wanted to take a look. Or maybe, if some time appears in the future for this, it could be a good thing to reference. 

I definitely will take a look, but I can't commit to anything since I have no idea about Safari extensions.

**Comment by gggritso** [comment]
Yeah, absolutely. Sorry for the delay, I spent the past week moving so it’s been quite hectic.

Adding settings to a Safari extensions has three main aspects:
1. using the Extension Builder to add extension settings
2. setting up communication between the page script and the extension page
3. making the page script flexible enough to accept configurable shortcuts

At a minimum I recommend you take a look at the [Extension Builder documentation](https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/UsingExtensionBuilder/UsingExtensionBuilder.html) to get acquainted with all the terminology. In broad strokes, the extension has a main script (which listens to the keyboard, and appends hints to the page) and an extension page (which fires off commands to Safari to close tabs, go back in history, etc.) There is a separation between the two because the main application script is _not allowed_ to control the browser, for security reasons. It has to send messages to the extension _page_, which _is_ allowed to control the browser (in some ways, anyway).

So, how would one go about adding configurable shortcuts? I think the best way is to see how the blacklist option is implemented and work from there. Step one is to load the extension into Extension Builder (see documentation for an overview) to see the options that already exist. Right now there is only one, which is the blacklist (you can see that it’s stored in the code as `Settings.plist`). You can add a new option here.

The second step is to _pass_ those options to the actual page script. If you open `vimmy.html` you’ll see a function called `announceBlackListToTab`. This function is called when settings are changed by the user in the extension preferences, and it’s also fired when the extension boots, so it can load the settings before it starts. You’ll need to write a similar function to announce when the keyboard configuration changes.

The third step is to actually use the settings. In `vimmy.js` check out the `checkBlackListStatus` function. You’ll notice that it is ran whenever the `newBlacklistedURLs` event is fired from `vimmy.html`. You’ll need to add similar logic to respond to when keyboard shortcuts change.

Lastly, you’ll want to make the actual keyboard shortcuts configurable. Right now, there’s a giant if-else statement to act on shortcuts, and everything is hard-coded. What I imagine you might like to do is instead of `if ( key === 'ctrl+u' )` change everything to use variables like `if ( key === SCROLL_UP_SHORTCUT )` and set `SCROLL_UP_SHORTCUT` when the settings from the UI are changed.

If you’d like more specific information I might be able to help you out, but I do recommend checking out the extension source code as it stands right now. I think you’ll quickly see how it’s laid out and what changes are required.
