### ISSUE TITLE
Copy Link

### ISSUE THREAD

**Issue by horak** [gggritso/Vimmy.safariextension#36]
It would be neat to be able to copy a selected link. Maybe using "L".

**Comment by gggritso** [comment]
I will look into this. Depends entirely on whether I can find a sane API to use the system clipboard, which might not be doable.

**Comment by gggritso** [comment]
Unfortunately Safari doesn’t support the `ClipboardEvent` constructor, so using the clipboard would require using some sort of third-party library, and those are usually Flash-based. This is a no-go from my perspective, since it makes the whole thing a lot more complicated and strange. Sorry to deny you a feature, but I really feel like it’s just not worth it.

**Comment by horak** [comment]
No problem. If I need it that badly, I'll build it. Thanks for looking into this 👍

**Comment by SmilinBrian** [comment]
Late to this party, but the functionality sounds interesting.

What if the Vimmy command was to "reveal" the URL of the link that was selected?

That is, when the link is selected show some kind of overlay with a form field holding the URL string, and the field content pre-selected so that Command-C would allow Copying. Escape would dismiss the display.

Flickr does this when you tell it you want the "share" URL for an image, Dropbox.com does it for the "share this file" URL, I'm sure there are other similar examples.
