### ISSUE TITLE
Allow more simple commands for vimmy

### ISSUE THREAD

**Issue by 0x0o** [gggritso/Vimmy.safariextension#46]
`ctrl-d`, `ctrl-u` are not the most direct way, Please at least add this command:

`d` to move down half a page
`u` to move up half a page

**Comment by rubenvarela** [comment]
- `f` is taken. 
- `d` moves down in a page
- `u` moves up in a page

Not 100% sure what the request is.

**Comment by 0x0o** [comment]
@rubenvarela sorry for the careless, I updated the description, I think Vimium Chrome Extension
s command, Like `d` Scroll a half page down, `u` to Scroll a half page up are simple than `ctrl-d`, `ctrl-u`.  

there are no `d` moves down in a page, `u` moves up in a page on [vimmy](http://gggritso.com/Vimmy.safariextension/)

**Comment by rubenvarela** [comment]
Could I have been in the wrong browser? 😞

*Edit*

I was >.> Firefox with VimFX

**Comment by gggritso** [comment]
In Vim (and editors that support Vim bindings) `d` deletes in visual mode, and `u` is undo. I'd rather not remap these familiar commands to something different, _especially_ since there are already very simple commands to do this exact same thing in the extension. How much trouble is that `ctrl-`, really?

**Comment by 0x0o** [comment]
Maybe I just familiar with Vimium
