### ISSUE TITLE
Add option for yellow tags like vimium

### ISSUE THREAD

**Issue by danielcompton** [gggritso/Vimmy.safariextension#48]
I prefer Vimium's style of yellow tags on black text, as I find them much more readable, especially on pages with dark backgrounds, e.g.: 

<img width="996" alt="screenshot of safari 24-04-17 4-01-23 pm" src="https://cloud.githubusercontent.com/assets/811954/25322036/47e0046a-2907-11e7-9f88-b743d882ec58.png">

In #23 ChrisLTD showed a forked version that had Vimium style tags. Would it be ok to add this as an option, or give a stylesheet override?

**Comment by eproxus** [comment]
I'd also like an option to position the tags above the links instead of on the side. Frequently, link hints cover each other (for example, with a sidebar menu next to links in main content). Also, I find it hard to know which hint belongs to which link, as in the GitHub example above to the right, where the hints for one link end up covering another link.

I was the original author of the link hint CSS in Vimium, and I'd be happy to contribute an updated style for Vimmy if needed.

**Comment by gggritso** [comment]
But not the rotated links option?

**Comment by eproxus** [comment]
After thinking a bit about it, I've come to the conclusion that link hints to the side is not the best way to implement this feature. The feature is trying to add extra elements to a page, which supplement the links already on the page. Adding them to the side, is like squeezing in extra elements between the existing elements already on a page, which is bound to create problems on the majority of pages. Rotating and switching sides for the hints are only partial solutions, as there are edge cases that will never work. The rotating seems to be randomly employed on some pages, but not others. Examples that are problematic:

* Placing hints to the side will overlap when two links are next to each other, taking up the entirety of the width (with links above and below which prevents rotating from being effective)
* Placing hints to the right is unintuitive when the link element is very broad but the content is left-aligned (this would also need adjustments for right-to-left languages, such as Arabic, as everything would need to be mirrored)

Placing hints on top of the links solves many problems, both layout wise and cognitive.

**Comment by gggritso** [comment]
Links on top don’t work when links are vertically aligned, like in sidebars (see Wikipedia). Rotated links that change sides and have a chevron to point to the correct link are the best method I’ve found and I’m doing to stick with it unless someone comes up with a solution that’s a clear winner.

If you’re truly unhappy with the link situation, it honestly might be a good time to fork the extension for yourself. I understand that I have a responsibility to maintain the extension but the hint positioning is one of the key value propositions of this extension over the others (for me, anyway) so I’m reluctant to change it.

Regardless, that’s neither here or there since this issue is about yellow links, so let’s talk about that. I’m not a huge fan of those yellow links, but I think adding a “high contrast” mode for people who prefer them is a reasonable request. I’m testing them out locally right now, and this is the scheme I’m going with right now:

![screen shot 2017-05-13 at 7 49 21 am](https://cloud.githubusercontent.com/assets/989898/26025246/58a1a67e-37b1-11e7-8ce0-2620475bb4a4.png)
![screen shot 2017-05-13 at 7 49 59 am](https://cloud.githubusercontent.com/assets/989898/26025247/58ac4840-37b1-11e7-87fb-f7e221dfe2f3.png)
![screen shot 2017-05-13 at 7 50 26 am](https://cloud.githubusercontent.com/assets/989898/26025248/58ad44d4-37b1-11e7-9eae-9fb7682eadb1.png)

I’m looking for feedback on the colours. If you want to just link the hex codes for colours that you like, I’m very open to that.

**Comment by eproxus** [comment]
@gggritso For links on top, would it be possible to copy the styles from the original CSS when it comes to text alignment? That would solve most alignment stuff properly. Plus, I think those cases are way more rare than all the problems with the links to the side.

**Comment by eproxus** [comment]
Regarding the link colors, it's hard to tell because of the small screenshots, but I'd suggest a darker yellow/orange outline so that they're clearly visible on yellow backgrounds as well. A good test case would be a page with the same background color as the link hint itself. If it's eligible there it should be eligible elsewhere (this is currently not the case with the black links, hence this issue).

**Comment by gggritso** [comment]
Firstly, I’m doing to dig my heels in with the label alignment. It’s what I prefer, and was a major reason why I even wrote this extension. If someone (cough) wants to put in a PR adding a different optional alignment strategy, I’d be happy to review and help merge it. Secondly, I’m shipping high contrast links! I’m personally happy with the colour scheme, but I’m open to input once it’s been in use.

**Comment by eproxus** [comment]
@gggritso Two pages I found troublesome with the link alignment was http://www.eurogamer.net and https://news.ycombinator.com, in case you need some examples to work with.

**Comment by gggritso** [comment]
Absolutely, that’s always very helpful! On Eurogamer, which ones are giving you trouble?

**Comment by eproxus** [comment]
Can't confirm because I'm on mobile, but I think it was the sidebar hints overlapping with the article hints to the right of the sidebar

**Comment by gggritso** [comment]
Hm, the sidebar links look totally fine to me...

**Comment by eproxus** [comment]
I was referring to the link hint overlap 
<img width="353" alt="screen shot 2017-08-07 at 13 37 12" src="https://user-images.githubusercontent.com/112878/29025132-97683eb0-7b75-11e7-80d0-4f6f6d7d02b3.png">

**Comment by gggritso** [comment]
Ah, I see what you mean. That’s a fair point. However in this case, if the hints were positioned above the links, wouldn’t that just make things even more confusing?

**Comment by eproxus** [comment]
I'n my opinion I think that is the clearest option, as can be seen from Vimium (and all other Vim-like extensions I know of):

<img width="558" alt="screen shot 2017-08-14 at 09 03 59" src="https://user-images.githubusercontent.com/112878/29261417-a0d5a2c6-80cf-11e7-9241-70056aab1326.png">

**Comment by gggritso** [comment]
So, something like this?
![screen shot 2017-08-17 at 10 44 08 pm](https://user-images.githubusercontent.com/989898/29442120-a776182e-839d-11e7-9c31-945d55c6e3d5.png)

**Comment by eproxus** [comment]
It's to my preference, but maybe not to everyone's 😄 I for one would love that as an option!

**Comment by gggritso** [comment]
Okay. I decided that being obstinate about this is counter-productive. The option to use what will be called “basic hints” will be in the next version.

**Comment by gggritso** [comment]
Vimmy `0.11.0` is now available with this feature.

**Comment by danielcompton** [comment]
Thanks heaps! Would you be able to publish the `safariextz` file in the release?

**Comment by gggritso** [comment]
Yes sorry! Upload didn’t work properly the first time for some reason.

**Comment by danielcompton** [comment]
Nice, thanks! I noticed that 0.10.1 is in the Safari extension store. Have they started accepting new versions again?

**Comment by gggritso** [comment]
Good question. They’re notoriously unresponsive when I upload new versions, so I usually rely on auto-update to take care of the version problem for me. I’ll try and submit a new version this week.
